import { validateFASTA, parseFASTA } from "./handleFASTA";

test("Validates single FASTA entry", async () => {
  await expect(
    validateFASTA(`>VIOA_CHRV4
MKHSSDICIVGAGISGLTCASHLLDSPACRGLSLRIFDMQQEAGGRIRSKMLDGKASIEL
GAGRYSPQLHPHFQSAMQHYSQKSEVYPFTQLKFKSHVQQKLKRAMNELSPRLKEHGKES
FLQFVSRYQGHDSAVGMIRSMGYDALFLPDISAEMAYDIVGKHPEIQSVTDNDANQWFAA
ETGFAGLIQGIKAKVKAAGARFSLGYRLLSVRTDGDGYLLQLAGDDGWKLEHRTRHLILA
IPPSAMAGLNVDFPEAWSGARYGSLPLFKGFLTYGEPWWLDYKLDDQVLIVDNPLRKIYF
KGDKYLFFYTDSEMANYWRGCVAEGEDGYLEQIRTHLASALGIVRERIPQPLAHVHKYWA
GVEFCRDSDIDHPSALSHRDSGIIACSDAYTEHCGWMEGGLLSAREASRLLLQRIAI`)
  ).resolves.toBeUndefined(); //.rejects.toThrow("I should fail");
});

test("Validates multi FASTA entry", async () => {
  await expect(
    validateFASTA(`>BAB16373.1 keratin, partial [Paralichthys olivaceus]
KNQRELEAWLQTQSESLSKEVAVKTEVLQTTKAEISDLRRTMQNLEIELQSQLSMKAALEGTLSDTECRY
SMQLQSLQIQVTSLEEQLMQLRADMERQNQEYNILLDIKTRLEMEIAEY

>VIOA_CHRV4
MKHSSDICIVGAGISGLTCASHLLDSPACRGLSLRIFDMQQEAGGRIRSKMLDGKASIEL
GAGRYSPQLHPHFQSAMQHYSQKSEVYPFTQLKFKSHVQQKLKRAMNELSPRLKEHGKES
FLQFVSRYQGHDSAVGMIRSMGYDALFLPDISAEMAYDIVGKHPEIQSVTDNDANQWFAA
ETGFAGLIQGIKAKVKAAGARFSLGYRLLSVRTDGDGYLLQLAGDDGWKLEHRTRHLILA
IPPSAMAGLNVDFPEAWSGARYGSLPLFKGFLTYGEPWWLDYKLDDQVLIVDNPLRKIYF
KGDKYLFFYTDSEMANYWRGCVAEGEDGYLEQIRTHLASALGIVRERIPQPLAHVHKYWA
GVEFCRDSDIDHPSALSHRDSGIIACSDAYTEHCGWMEGGLLSAREASRLLLQRIAI`)
  ).resolves.toBeUndefined();
});

test("Fails for empty sequence", async () => {
  await expect(
    validateFASTA(`>BAB16373.1 keratin, partial [Paralichthys olivaceus]
KNQRELEAWLQTQSESLSKEVAVKTEVLQTTKAEISDLRRTMQNLEIELQSQLSMKAALEGTLSDTECRY
SMQLQSLQIQVTSLEEQLMQLRADMERQNQEYNILLDIKTRLEMEIAEY

>VIOA_CHRV4`)
  ).rejects.toThrow("Empty sequence on L5");
});

test("Fails for invalid sequence", async () => {
  await expect(
    validateFASTA(`>BAB16373.1 keratin, partial [Paralichthys olivaceus]
KNQRELEAWLQTQSESLSKEVAVKTEVLQTTKAEISDLRRTMQNLEIELQSQLSMKAALEGTLSDTECRY
SMQLQSLQIQVTSLEEQLMQLRADMERQNBEYNILLDIKTRLEMEIAEY`)
  ).rejects.toThrow("Disallowed character on L3");
});

test("Parses a single FASTA entry", async () => {
  await expect(
    parseFASTA(`>VIOA_CHRV4
MKHSSDICIVGAGISGLTCASHLLDSPACRGLSLRIFDMQQEAGGRIRSKMLDGKASIEL
GAGRYSPQLHPHFQSAMQHYSQKSEVYPFTQLKFKSHVQQKLKRAMNELSPRLKEHGKES
FLQFVSRYQGHDSAVGMIRSMGYDALFLPDISAEMAYDIVGKHPEIQSVTDNDANQWFAA
ETGFAGLIQGIKAKVKAAGARFSLGYRLLSVRTDGDGYLLQLAGDDGWKLEHRTRHLILA
IPPSAMAGLNVDFPEAWSGARYGSLPLFKGFLTYGEPWWLDYKLDDQVLIVDNPLRKIYF
KGDKYLFFYTDSEMANYWRGCVAEGEDGYLEQIRTHLASALGIVRERIPQPLAHVHKYWA
GVEFCRDSDIDHPSALSHRDSGIIACSDAYTEHCGWMEGGLLSAREASRLLLQRIAI`)
  ).resolves.toEqual([
    {
      id: "VIOA_CHRV4",
      data:
        "MKHSSDICIVGAGISGLTCASHLLDSPACRGLSLRIFDMQQEAGGRIRSKMLDGKASIEL" +
        "GAGRYSPQLHPHFQSAMQHYSQKSEVYPFTQLKFKSHVQQKLKRAMNELSPRLKEHGKES" +
        "FLQFVSRYQGHDSAVGMIRSMGYDALFLPDISAEMAYDIVGKHPEIQSVTDNDANQWFAA" +
        "ETGFAGLIQGIKAKVKAAGARFSLGYRLLSVRTDGDGYLLQLAGDDGWKLEHRTRHLILA" +
        "IPPSAMAGLNVDFPEAWSGARYGSLPLFKGFLTYGEPWWLDYKLDDQVLIVDNPLRKIYF" +
        "KGDKYLFFYTDSEMANYWRGCVAEGEDGYLEQIRTHLASALGIVRERIPQPLAHVHKYWA" +
        "GVEFCRDSDIDHPSALSHRDSGIIACSDAYTEHCGWMEGGLLSAREASRLLLQRIAI",
    },
  ]);
});

test("Parses multiple FASTA entries", async () => {
  await expect(
    parseFASTA(`>BAB16373.1 keratin, partial [Paralichthys olivaceus]
KNQRELEAWLQTQSESLSKEVAVKTEVLQTTKAEISDLRRTMQNLEIELQSQLSMKAALEGTLSDTECRY
SMQLQSLQIQVTSLEEQLMQLRADMERQNQEYNILLDIKTRLEMEIAEY

>VIOA_CHRV4
MKHSSDICIVGAGISGLTCASHLLDSPACRGLSLRIFDMQQEAGGRIRSKMLDGKASIEL
GAGRYSPQLHPHFQSAMQHYSQKSEVYPFTQLKFKSHVQQKLKRAMNELSPRLKEHGKES
FLQFVSRYQGHDSAVGMIRSMGYDALFLPDISAEMAYDIVGKHPEIQSVTDNDANQWFAA
ETGFAGLIQGIKAKVKAAGARFSLGYRLLSVRTDGDGYLLQLAGDDGWKLEHRTRHLILA
IPPSAMAGLNVDFPEAWSGARYGSLPLFKGFLTYGEPWWLDYKLDDQVLIVDNPLRKIYF
KGDKYLFFYTDSEMANYWRGCVAEGEDGYLEQIRTHLASALGIVRERIPQPLAHVHKYWA
GVEFCRDSDIDHPSALSHRDSGIIACSDAYTEHCGWMEGGLLSAREASRLLLQRIAI`)
  ).resolves.toEqual([
    {
      id: "BAB16373.1",
      data:
        "KNQRELEAWLQTQSESLSKEVAVKTEVLQTTKAEISDLRRTMQNLEIELQSQLSMKAALEGTLSDTECRY" +
        "SMQLQSLQIQVTSLEEQLMQLRADMERQNQEYNILLDIKTRLEMEIAEY",
    },
    {
      id: "VIOA_CHRV4",
      data:
        "MKHSSDICIVGAGISGLTCASHLLDSPACRGLSLRIFDMQQEAGGRIRSKMLDGKASIEL" +
        "GAGRYSPQLHPHFQSAMQHYSQKSEVYPFTQLKFKSHVQQKLKRAMNELSPRLKEHGKES" +
        "FLQFVSRYQGHDSAVGMIRSMGYDALFLPDISAEMAYDIVGKHPEIQSVTDNDANQWFAA" +
        "ETGFAGLIQGIKAKVKAAGARFSLGYRLLSVRTDGDGYLLQLAGDDGWKLEHRTRHLILA" +
        "IPPSAMAGLNVDFPEAWSGARYGSLPLFKGFLTYGEPWWLDYKLDDQVLIVDNPLRKIYF" +
        "KGDKYLFFYTDSEMANYWRGCVAEGEDGYLEQIRTHLASALGIVRERIPQPLAHVHKYWA" +
        "GVEFCRDSDIDHPSALSHRDSGIIACSDAYTEHCGWMEGGLLSAREASRLLLQRIAI",
    },
  ]);
});
