import { validateFASTA } from "./validateFASTA";

test("Validates single FASTA entry", () => {
  expect(
    validateFASTA(`>VIOA_CHRV4
MKHSSDICIVGAGISGLTCASHLLDSPACRGLSLRIFDMQQEAGGRIRSKMLDGKASIEL
GAGRYSPQLHPHFQSAMQHYSQKSEVYPFTQLKFKSHVQQKLKRAMNELSPRLKEHGKES
FLQFVSRYQGHDSAVGMIRSMGYDALFLPDISAEMAYDIVGKHPEIQSVTDNDANQWFAA
ETGFAGLIQGIKAKVKAAGARFSLGYRLLSVRTDGDGYLLQLAGDDGWKLEHRTRHLILA
IPPSAMAGLNVDFPEAWSGARYGSLPLFKGFLTYGEPWWLDYKLDDQVLIVDNPLRKIYF
KGDKYLFFYTDSEMANYWRGCVAEGEDGYLEQIRTHLASALGIVRERIPQPLAHVHKYWA
GVEFCRDSDIDHPSALSHRDSGIIACSDAYTEHCGWMEGGLLSAREASRLLLQRIAI`)
  ).resolves.toBeUndefined();
});

test("Validates multi FASTA entry", () => {
  expect(
    validateFASTA(`>BAB16373.1 keratin, partial [Paralichthys olivaceus]
KNQRELEAWLQTQSESLSKEVAVKTEVLQTTKAEISDLRRTMQNLEIELQSQLSMKAALEGTLSDTECRY
SMQLQSLQIQVTSLEEQLMQLRADMERQNQEYNILLDIKTRLEMEIAEY

>VIOA_CHRV4
MKHSSDICIVGAGISGLTCASHLLDSPACRGLSLRIFDMQQEAGGRIRSKMLDGKASIEL
GAGRYSPQLHPHFQSAMQHYSQKSEVYPFTQLKFKSHVQQKLKRAMNELSPRLKEHGKES
FLQFVSRYQGHDSAVGMIRSMGYDALFLPDISAEMAYDIVGKHPEIQSVTDNDANQWFAA
ETGFAGLIQGIKAKVKAAGARFSLGYRLLSVRTDGDGYLLQLAGDDGWKLEHRTRHLILA
IPPSAMAGLNVDFPEAWSGARYGSLPLFKGFLTYGEPWWLDYKLDDQVLIVDNPLRKIYF
KGDKYLFFYTDSEMANYWRGCVAEGEDGYLEQIRTHLASALGIVRERIPQPLAHVHKYWA
GVEFCRDSDIDHPSALSHRDSGIIACSDAYTEHCGWMEGGLLSAREASRLLLQRIAI`)
  ).resolves.toBeUndefined();
});

test("Fails for empty sequence", () => {
  expect(
    validateFASTA(`>BAB16373.1 keratin, partial [Paralichthys olivaceus]
KNQRELEAWLQTQSESLSKEVAVKTEVLQTTKAEISDLRRTMQNLEIELQSQLSMKAALEGTLSDTECRY
SMQLQSLQIQVTSLEEQLMQLRADMERQNQEYNILLDIKTRLEMEIAEY

>VIOA_CHRV4`)
  ).rejects.toBe("Empty sequence on L5");
});

test("Fails for invalid sequence", () => {
  expect(
    validateFASTA(`>BAB16373.1 keratin, partial [Paralichthys olivaceus]
KNQRELEAWLQTQSESLSKEVAVKTEVLQTTKAEISDLRRTMQNLEIELQSQLSMKAALEGTLSDTECRY
SMQLQSLQIQVTSLEEQLMQLRADMERQNBEYNILLDIKTRLEMEIAEY`)
  ).rejects.toBe("Disallowed character on L3");
});
